/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logicadepresentacion.gui;

import logicadeintegracion.gui.ControladorComisionGanada;

/**
 *
 * @author Alejandra Merino
 */
public class ComisionGanada extends javax.swing.JPanel {

  /**
   * Creates new form ComisionGanada
   */
  public ComisionGanada() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtDetalleComisionTotal = new javax.swing.JTextArea();
    btnConsultarGananciasPanel = new javax.swing.JPanel();
    btnConsultarGananciasLabel = new javax.swing.JLabel();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Consulte las ganancias del banco");

    jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
    jLabel2.setText("Detalle de comisiones totales:");

    txtDetalleComisionTotal.setBackground(new java.awt.Color(255, 255, 255));
    txtDetalleComisionTotal.setColumns(20);
    txtDetalleComisionTotal.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
    txtDetalleComisionTotal.setRows(5);
    jScrollPane1.setViewportView(txtDetalleComisionTotal);

    btnConsultarGananciasLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
    btnConsultarGananciasLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultarGananciasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnConsultarGananciasLabel.setText("Consultar");
    btnConsultarGananciasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultarGananciasLabelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btnConsultarGananciasPanelLayout = new javax.swing.GroupLayout(btnConsultarGananciasPanel);
    btnConsultarGananciasPanel.setLayout(btnConsultarGananciasPanelLayout);
    btnConsultarGananciasPanelLayout.setHorizontalGroup(
      btnConsultarGananciasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnConsultarGananciasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    btnConsultarGananciasPanelLayout.setVerticalGroup(
      btnConsultarGananciasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnConsultarGananciasPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnConsultarGananciasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(175, 175, 175)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(353, 353, 353)
            .addComponent(btnConsultarGananciasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(168, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(77, 77, 77)
        .addComponent(jLabel1)
        .addGap(78, 78, 78)
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnConsultarGananciasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(284, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnConsultarGananciasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarGananciasLabelMouseClicked
    ControladorComisionGanada control = new ControladorComisionGanada ();
    control.controlarComisionesGanadasTotal();
    txtDetalleComisionTotal.setText(control.getMensaje());
  }//GEN-LAST:event_btnConsultarGananciasLabelMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel btnConsultarGananciasLabel;
  private javax.swing.JPanel btnConsultarGananciasPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtDetalleComisionTotal;
  // End of variables declaration//GEN-END:variables
}
