/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logicadepresentacion.gui;

import javax.swing.JOptionPane;
import logicadeintegracion.gui.ControladorSaldoActualDolares;
import logicadevalidacion.ValidacionCuenta;

/**
 *
 * @author Alejandra Merino
 */
public class ConsultaSaldoActualDolares extends javax.swing.JPanel {
  private ValidacionCuenta validacionCuenta;
  private ControladorSaldoActualDolares control;
  /**
   * Creates new form ConsultaSaldoActualDolares
   */
  public ConsultaSaldoActualDolares() {
    initComponents();
    validacionCuenta = new ValidacionCuenta ();
    control = new ControladorSaldoActualDolares ();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtNumCuenta = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    txtPinActual = new javax.swing.JTextField();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtDetalleSaldoDolares = new javax.swing.JTextArea();
    btnConsultarDolaresPanel = new javax.swing.JPanel();
    btnConsultarDolares = new javax.swing.JLabel();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Consultar saldo actual en dólares");

    jLabel2.setText("Ingrese su número de cuenta:");

    jLabel3.setText("Ingrese el PIN de su cuenta:");

    jLabel4.setText("Detalle:");

    txtDetalleSaldoDolares.setColumns(20);
    txtDetalleSaldoDolares.setRows(5);
    jScrollPane1.setViewportView(txtDetalleSaldoDolares);

    btnConsultarDolaresPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnConsultarDolares.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
    btnConsultarDolares.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultarDolares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnConsultarDolares.setText("Consultar");
    btnConsultarDolares.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultarDolaresMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btnConsultarDolaresPanelLayout = new javax.swing.GroupLayout(btnConsultarDolaresPanel);
    btnConsultarDolaresPanel.setLayout(btnConsultarDolaresPanelLayout);
    btnConsultarDolaresPanelLayout.setHorizontalGroup(
      btnConsultarDolaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultarDolaresPanelLayout.createSequentialGroup()
        .addComponent(btnConsultarDolares, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        .addContainerGap())
    );
    btnConsultarDolaresPanelLayout.setVerticalGroup(
      btnConsultarDolaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnConsultarDolaresPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnConsultarDolares, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(177, 177, 177)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
          .addComponent(jLabel4)
          .addComponent(txtPinActual)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSeparator1)
          .addComponent(txtNumCuenta)
          .addComponent(jLabel3)
          .addComponent(jSeparator2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(375, Short.MAX_VALUE)
        .addComponent(btnConsultarDolaresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(355, 355, 355))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(79, 79, 79)
        .addComponent(jLabel1)
        .addGap(48, 48, 48)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPinActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(26, 26, 26)
        .addComponent(btnConsultarDolaresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(198, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnConsultarDolaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarDolaresMouseClicked
    validacionCuenta.validarDatosPrevioRetiro(txtNumCuenta.getText(), txtPinActual.getText());
    if(validacionCuenta.esValido()) {
      control.controlarSaldoActualDolares(txtNumCuenta.getText());
      validacionCuenta.setResultado(control.getMensaje());
      txtDetalleSaldoDolares.setText(validacionCuenta.getResultado());
    } else {
      JOptionPane.showMessageDialog(this, validacionCuenta.getResultado());
    }
  }//GEN-LAST:event_btnConsultarDolaresMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel btnConsultarDolares;
  private javax.swing.JPanel btnConsultarDolaresPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JTextArea txtDetalleSaldoDolares;
  private javax.swing.JTextField txtNumCuenta;
  private javax.swing.JTextField txtPinActual;
  // End of variables declaration//GEN-END:variables
}
