/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logicadepresentacion.gui;

import javax.swing.JOptionPane;
import logicadeintegracion.gui.ControladorEstadoCuentaDolares;
import logicadevalidacion.ValidacionCuenta;

/**
 *
 * @author Alejandra Merino
 */
public class EstadoCuentaDolares extends javax.swing.JPanel {
  private ValidacionCuenta validacionCuenta;
  private ControladorEstadoCuentaDolares control;
  /**
   * Creates new form EstadoCuentaDolares
   */
  public EstadoCuentaDolares() {
    initComponents();
    validacionCuenta = new ValidacionCuenta ();
    control = new ControladorEstadoCuentaDolares ();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtNumCuenta = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    txtPinActual = new javax.swing.JTextField();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtDetalleEstadoCuentaDolares = new javax.swing.JTextArea();
    btnConsultarEstadoCuentaDolaresPanel = new javax.swing.JPanel();
    btnConsultarEstadoCuentaDolaresLabel = new javax.swing.JLabel();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Consulte el estado de su cuenta en dólares");

    jLabel2.setText("Ingrese su número de cuenta:");

    txtNumCuenta.setBackground(new java.awt.Color(255, 255, 255));
    txtNumCuenta.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
    txtNumCuenta.setForeground(new java.awt.Color(102, 102, 102));
    txtNumCuenta.setBorder(null);

    jLabel3.setText("Ingrese el PIN de su cuenta:");

    txtPinActual.setBackground(new java.awt.Color(255, 255, 255));
    txtPinActual.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
    txtPinActual.setForeground(new java.awt.Color(102, 102, 102));
    txtPinActual.setBorder(null);

    jLabel4.setText("Detalle de su cuenta:");

    txtDetalleEstadoCuentaDolares.setBackground(new java.awt.Color(255, 255, 255));
    txtDetalleEstadoCuentaDolares.setColumns(20);
    txtDetalleEstadoCuentaDolares.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
    txtDetalleEstadoCuentaDolares.setForeground(new java.awt.Color(102, 102, 102));
    txtDetalleEstadoCuentaDolares.setRows(5);
    jScrollPane1.setViewportView(txtDetalleEstadoCuentaDolares);

    btnConsultarEstadoCuentaDolaresLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
    btnConsultarEstadoCuentaDolaresLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultarEstadoCuentaDolaresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnConsultarEstadoCuentaDolaresLabel.setText("Consultar");
    btnConsultarEstadoCuentaDolaresLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnConsultarEstadoCuentaDolaresLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultarEstadoCuentaDolaresLabelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btnConsultarEstadoCuentaDolaresPanelLayout = new javax.swing.GroupLayout(btnConsultarEstadoCuentaDolaresPanel);
    btnConsultarEstadoCuentaDolaresPanel.setLayout(btnConsultarEstadoCuentaDolaresPanelLayout);
    btnConsultarEstadoCuentaDolaresPanelLayout.setHorizontalGroup(
      btnConsultarEstadoCuentaDolaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnConsultarEstadoCuentaDolaresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    btnConsultarEstadoCuentaDolaresPanelLayout.setVerticalGroup(
      btnConsultarEstadoCuentaDolaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnConsultarEstadoCuentaDolaresPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnConsultarEstadoCuentaDolaresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(139, 139, 139)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
          .addComponent(jLabel4)
          .addComponent(jLabel3)
          .addComponent(jLabel2)
          .addComponent(txtNumCuenta)
          .addComponent(jSeparator1)
          .addComponent(txtPinActual)
          .addComponent(jSeparator2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnConsultarEstadoCuentaDolaresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(359, 359, 359))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(67, 67, 67)
        .addComponent(jLabel1)
        .addGap(27, 27, 27)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPinActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnConsultarEstadoCuentaDolaresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(39, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnConsultarEstadoCuentaDolaresLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarEstadoCuentaDolaresLabelMouseClicked
    validacionCuenta.validarDatosPrevioRetiro(txtNumCuenta.getText(), 
            txtPinActual.getText());
    if (validacionCuenta.esValido()) {
      control.controlarEstadoCuentaDolares(txtNumCuenta.getText());
      txtDetalleEstadoCuentaDolares.setText(control.getMensaje());
    } else {
      JOptionPane.showMessageDialog(this, validacionCuenta.resultado);
    }
  }//GEN-LAST:event_btnConsultarEstadoCuentaDolaresLabelMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel btnConsultarEstadoCuentaDolaresLabel;
  private javax.swing.JPanel btnConsultarEstadoCuentaDolaresPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JTextArea txtDetalleEstadoCuentaDolares;
  private javax.swing.JTextField txtNumCuenta;
  private javax.swing.JTextField txtPinActual;
  // End of variables declaration//GEN-END:variables
}
