/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logicadepresentacion.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import logicacreacional.SimpleValidacionFactory;

/**
 *
 * @author Alejandra Merino
 */
public class Menu extends javax.swing.JFrame {
    
  /**
   * Creates new form Menu
   */
  public Menu() {
    
    initComponents();
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jPanel19 = new javax.swing.JPanel();
    bg = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    btnRegistrarCliente = new javax.swing.JPanel();
    btnRegistrarClienteLabel = new javax.swing.JLabel();
    principal = new javax.swing.JLabel();
    btnCrearCuenta = new javax.swing.JPanel();
    btnCrearCuentaL = new javax.swing.JLabel();
    btnConsultarClientePanel = new javax.swing.JPanel();
    btnConsultarclienteLabel = new javax.swing.JLabel();
    btnConsultaCuentaPanel = new javax.swing.JPanel();
    btnConsultaCuentaLabel = new javax.swing.JLabel();
    btnCambiarPinPanel = new javax.swing.JPanel();
    btnCambiarPinLabel = new javax.swing.JLabel();
    btnDepositarPanel = new javax.swing.JPanel();
    btnDepositarLabel = new javax.swing.JLabel();
    btnRetirarPanel = new javax.swing.JPanel();
    btnRetirarLabel = new javax.swing.JLabel();
    btnTransferirPanel = new javax.swing.JPanel();
    btnTransferirLabel = new javax.swing.JLabel();
    btnTipoCambioPanel = new javax.swing.JPanel();
    btnTipoCambioLabel = new javax.swing.JLabel();
    btnConsultarSaldoActualPanel = new javax.swing.JPanel();
    btnConsultarSaldoActualLabel = new javax.swing.JLabel();
    btnConsultarSaldoDolaresPanel = new javax.swing.JPanel();
    btnConsultarSaldoDolaresLabel = new javax.swing.JLabel();
    btnEstadoCuentaPanel = new javax.swing.JPanel();
    btnEstadoCuentaLabel = new javax.swing.JLabel();
    btnEstadoCuentaDolarPanel = new javax.swing.JPanel();
    btnEstadoCuentaDolarLabel = new javax.swing.JLabel();
    btnEstatusPanel = new javax.swing.JPanel();
    btnEstatusLabel = new javax.swing.JLabel();
    btnComisionTotalPanel = new javax.swing.JPanel();
    btnComisionTotalLabel = new javax.swing.JLabel();
    btnComisionCuentaPanel = new javax.swing.JPanel();
    btnComisionCuentaLabel = new javax.swing.JLabel();
    btnSalirPanel = new javax.swing.JPanel();
    btnSalirLabel = new javax.swing.JLabel();
    content = new javax.swing.JPanel();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    jLabel22 = new javax.swing.JLabel();

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 610, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 500, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
    jPanel19.setLayout(jPanel19Layout);
    jPanel19Layout.setHorizontalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel19Layout.setVerticalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setLocationByPlatform(true);
    setResizable(false);

    bg.setBackground(new java.awt.Color(255, 255, 255));
    bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBackground(new java.awt.Color(49, 24, 140));

    btnRegistrarCliente.setBackground(new java.awt.Color(49, 24, 140));

    btnRegistrarClienteLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnRegistrarClienteLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnRegistrarClienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnRegistrarClienteLabel.setText("Registrar un cliente");
    btnRegistrarClienteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRegistrarClienteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnRegistrarClienteLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnRegistrarClienteLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnRegistrarClienteLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnRegistrarClienteLayout = new javax.swing.GroupLayout(btnRegistrarCliente);
    btnRegistrarCliente.setLayout(btnRegistrarClienteLayout);
    btnRegistrarClienteLayout.setHorizontalGroup(
      btnRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRegistrarClienteLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnRegistrarClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnRegistrarClienteLayout.setVerticalGroup(
      btnRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnRegistrarClienteLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
    );

    principal.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
    principal.setForeground(new java.awt.Color(255, 255, 255));
    principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    principal.setText("iBanco");
    principal.setToolTipText("");
    principal.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        principalMouseClicked(evt);
      }
    });

    btnCrearCuenta.setBackground(new java.awt.Color(49, 24, 140));
    btnCrearCuenta.setPreferredSize(new java.awt.Dimension(200, 31));

    btnCrearCuentaL.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnCrearCuentaL.setForeground(new java.awt.Color(255, 255, 255));
    btnCrearCuentaL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnCrearCuentaL.setText("Crear cuenta");
    btnCrearCuentaL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnCrearCuentaL.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnCrearCuentaLMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnCrearCuentaLMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnCrearCuentaLMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnCrearCuentaLayout = new javax.swing.GroupLayout(btnCrearCuenta);
    btnCrearCuenta.setLayout(btnCrearCuentaLayout);
    btnCrearCuentaLayout.setHorizontalGroup(
      btnCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearCuentaLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnCrearCuentaL, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnCrearCuentaLayout.setVerticalGroup(
      btnCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearCuentaLayout.createSequentialGroup()
        .addComponent(btnCrearCuentaL, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        .addContainerGap())
    );

    btnConsultarClientePanel.setBackground(new java.awt.Color(49, 24, 140));
    btnConsultarClientePanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnConsultarclienteLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnConsultarclienteLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnConsultarclienteLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultarclienteLabel.setText("Consultar cliente");
    btnConsultarclienteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnConsultarclienteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultarclienteLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnConsultarclienteLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnConsultarclienteLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnConsultarClientePanelLayout = new javax.swing.GroupLayout(btnConsultarClientePanel);
    btnConsultarClientePanel.setLayout(btnConsultarClientePanelLayout);
    btnConsultarClientePanelLayout.setHorizontalGroup(
      btnConsultarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultarClientePanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnConsultarclienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnConsultarClientePanelLayout.setVerticalGroup(
      btnConsultarClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultarClientePanelLayout.createSequentialGroup()
        .addContainerGap(10, Short.MAX_VALUE)
        .addComponent(btnConsultarclienteLabel)
        .addContainerGap())
    );

    btnConsultaCuentaPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnConsultaCuentaPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnConsultaCuentaLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnConsultaCuentaLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnConsultaCuentaLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultaCuentaLabel.setText("Consultar cuenta");
    btnConsultaCuentaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnConsultaCuentaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultaCuentaLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnConsultaCuentaLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnConsultaCuentaLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnConsultaCuentaPanelLayout = new javax.swing.GroupLayout(btnConsultaCuentaPanel);
    btnConsultaCuentaPanel.setLayout(btnConsultaCuentaPanelLayout);
    btnConsultaCuentaPanelLayout.setHorizontalGroup(
      btnConsultaCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultaCuentaPanelLayout.createSequentialGroup()
        .addGap(0, 14, Short.MAX_VALUE)
        .addComponent(btnConsultaCuentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnConsultaCuentaPanelLayout.setVerticalGroup(
      btnConsultaCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnConsultaCuentaPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnConsultaCuentaLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnCambiarPinPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnCambiarPinPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnCambiarPinLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnCambiarPinLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnCambiarPinLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnCambiarPinLabel.setText("Cambiar PIN");
    btnCambiarPinLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnCambiarPinLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnCambiarPinLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnCambiarPinLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnCambiarPinLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnCambiarPinPanelLayout = new javax.swing.GroupLayout(btnCambiarPinPanel);
    btnCambiarPinPanel.setLayout(btnCambiarPinPanelLayout);
    btnCambiarPinPanelLayout.setHorizontalGroup(
      btnCambiarPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCambiarPinPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnCambiarPinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnCambiarPinPanelLayout.setVerticalGroup(
      btnCambiarPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnCambiarPinPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnCambiarPinLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnDepositarPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnDepositarPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnDepositarLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnDepositarLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnDepositarLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnDepositarLabel.setText("Depositar");
    btnDepositarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnDepositarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnDepositarLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnDepositarLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnDepositarLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnDepositarPanelLayout = new javax.swing.GroupLayout(btnDepositarPanel);
    btnDepositarPanel.setLayout(btnDepositarPanelLayout);
    btnDepositarPanelLayout.setHorizontalGroup(
      btnDepositarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDepositarPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnDepositarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnDepositarPanelLayout.setVerticalGroup(
      btnDepositarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnDepositarPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnDepositarLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnRetirarPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnRetirarPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnRetirarLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnRetirarLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnRetirarLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnRetirarLabel.setText("Retirar");
    btnRetirarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRetirarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnRetirarLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnRetirarLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnRetirarLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnRetirarPanelLayout = new javax.swing.GroupLayout(btnRetirarPanel);
    btnRetirarPanel.setLayout(btnRetirarPanelLayout);
    btnRetirarPanelLayout.setHorizontalGroup(
      btnRetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRetirarPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnRetirarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnRetirarPanelLayout.setVerticalGroup(
      btnRetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnRetirarPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnRetirarLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnTransferirPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnTransferirPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnTransferirLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnTransferirLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnTransferirLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnTransferirLabel.setText("Transferir");
    btnTransferirLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnTransferirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnTransferirLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnTransferirLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnTransferirLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnTransferirPanelLayout = new javax.swing.GroupLayout(btnTransferirPanel);
    btnTransferirPanel.setLayout(btnTransferirPanelLayout);
    btnTransferirPanelLayout.setHorizontalGroup(
      btnTransferirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTransferirPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnTransferirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnTransferirPanelLayout.setVerticalGroup(
      btnTransferirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnTransferirPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnTransferirLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnTipoCambioPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnTipoCambioPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnTipoCambioLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnTipoCambioLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnTipoCambioLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnTipoCambioLabel.setText("Tipo de cambio");
    btnTipoCambioLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnTipoCambioLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnTipoCambioLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnTipoCambioLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnTipoCambioLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnTipoCambioPanelLayout = new javax.swing.GroupLayout(btnTipoCambioPanel);
    btnTipoCambioPanel.setLayout(btnTipoCambioPanelLayout);
    btnTipoCambioPanelLayout.setHorizontalGroup(
      btnTipoCambioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTipoCambioPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnTipoCambioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnTipoCambioPanelLayout.setVerticalGroup(
      btnTipoCambioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnTipoCambioPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnTipoCambioLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnConsultarSaldoActualPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnConsultarSaldoActualPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnConsultarSaldoActualLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnConsultarSaldoActualLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnConsultarSaldoActualLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultarSaldoActualLabel.setText("Consultar saldo actual");
    btnConsultarSaldoActualLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnConsultarSaldoActualLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultarSaldoActualLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnConsultarSaldoActualLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnConsultarSaldoActualLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnConsultarSaldoActualPanelLayout = new javax.swing.GroupLayout(btnConsultarSaldoActualPanel);
    btnConsultarSaldoActualPanel.setLayout(btnConsultarSaldoActualPanelLayout);
    btnConsultarSaldoActualPanelLayout.setHorizontalGroup(
      btnConsultarSaldoActualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultarSaldoActualPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnConsultarSaldoActualLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnConsultarSaldoActualPanelLayout.setVerticalGroup(
      btnConsultarSaldoActualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnConsultarSaldoActualPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnConsultarSaldoActualLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnConsultarSaldoDolaresPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnConsultarSaldoDolaresPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnConsultarSaldoDolaresLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnConsultarSaldoDolaresLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultarSaldoDolaresLabel.setText("Consultar saldo actual dolares");
    btnConsultarSaldoDolaresLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnConsultarSaldoDolaresLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultarSaldoDolaresLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnConsultarSaldoDolaresLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnConsultarSaldoDolaresLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnConsultarSaldoDolaresPanelLayout = new javax.swing.GroupLayout(btnConsultarSaldoDolaresPanel);
    btnConsultarSaldoDolaresPanel.setLayout(btnConsultarSaldoDolaresPanelLayout);
    btnConsultarSaldoDolaresPanelLayout.setHorizontalGroup(
      btnConsultarSaldoDolaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultarSaldoDolaresPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnConsultarSaldoDolaresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnConsultarSaldoDolaresPanelLayout.setVerticalGroup(
      btnConsultarSaldoDolaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnConsultarSaldoDolaresPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnConsultarSaldoDolaresLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnEstadoCuentaPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnEstadoCuentaPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnEstadoCuentaLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnEstadoCuentaLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnEstadoCuentaLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnEstadoCuentaLabel.setText("Estado de cuenta");
    btnEstadoCuentaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnEstadoCuentaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnEstadoCuentaLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnEstadoCuentaLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnEstadoCuentaLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnEstadoCuentaPanelLayout = new javax.swing.GroupLayout(btnEstadoCuentaPanel);
    btnEstadoCuentaPanel.setLayout(btnEstadoCuentaPanelLayout);
    btnEstadoCuentaPanelLayout.setHorizontalGroup(
      btnEstadoCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEstadoCuentaPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnEstadoCuentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnEstadoCuentaPanelLayout.setVerticalGroup(
      btnEstadoCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnEstadoCuentaPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnEstadoCuentaLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnEstadoCuentaDolarPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnEstadoCuentaDolarPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnEstadoCuentaDolarLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnEstadoCuentaDolarLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnEstadoCuentaDolarLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnEstadoCuentaDolarLabel.setText("Estado de cuenta dolares");
    btnEstadoCuentaDolarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnEstadoCuentaDolarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnEstadoCuentaDolarLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnEstadoCuentaDolarLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnEstadoCuentaDolarLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnEstadoCuentaDolarPanelLayout = new javax.swing.GroupLayout(btnEstadoCuentaDolarPanel);
    btnEstadoCuentaDolarPanel.setLayout(btnEstadoCuentaDolarPanelLayout);
    btnEstadoCuentaDolarPanelLayout.setHorizontalGroup(
      btnEstadoCuentaDolarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEstadoCuentaDolarPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnEstadoCuentaDolarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnEstadoCuentaDolarPanelLayout.setVerticalGroup(
      btnEstadoCuentaDolarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnEstadoCuentaDolarPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnEstadoCuentaDolarLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnEstatusPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnEstatusPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnEstatusLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnEstatusLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnEstatusLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnEstatusLabel.setText("Estatus de cuenta");
    btnEstatusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnEstatusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnEstatusLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnEstatusLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnEstatusLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnEstatusPanelLayout = new javax.swing.GroupLayout(btnEstatusPanel);
    btnEstatusPanel.setLayout(btnEstatusPanelLayout);
    btnEstatusPanelLayout.setHorizontalGroup(
      btnEstatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEstatusPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnEstatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnEstatusPanelLayout.setVerticalGroup(
      btnEstatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnEstatusPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnEstatusLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnComisionTotalPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnComisionTotalPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnComisionTotalLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnComisionTotalLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnComisionTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnComisionTotalLabel.setText("Comisiones ganadas");
    btnComisionTotalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnComisionTotalLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnComisionTotalLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnComisionTotalLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnComisionTotalLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnComisionTotalPanelLayout = new javax.swing.GroupLayout(btnComisionTotalPanel);
    btnComisionTotalPanel.setLayout(btnComisionTotalPanelLayout);
    btnComisionTotalPanelLayout.setHorizontalGroup(
      btnComisionTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnComisionTotalPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnComisionTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnComisionTotalPanelLayout.setVerticalGroup(
      btnComisionTotalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnComisionTotalPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnComisionTotalLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnComisionCuentaPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnComisionCuentaPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnComisionCuentaLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnComisionCuentaLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnComisionCuentaLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnComisionCuentaLabel.setText("Comisiones ganadas por cuenta");
    btnComisionCuentaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnComisionCuentaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnComisionCuentaLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnComisionCuentaLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        btnComisionCuentaLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnComisionCuentaPanelLayout = new javax.swing.GroupLayout(btnComisionCuentaPanel);
    btnComisionCuentaPanel.setLayout(btnComisionCuentaPanelLayout);
    btnComisionCuentaPanelLayout.setHorizontalGroup(
      btnComisionCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnComisionCuentaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
    );
    btnComisionCuentaPanelLayout.setVerticalGroup(
      btnComisionCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnComisionCuentaPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnComisionCuentaLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    btnSalirPanel.setBackground(new java.awt.Color(49, 24, 140));
    btnSalirPanel.setPreferredSize(new java.awt.Dimension(200, 31));

    btnSalirLabel.setBackground(new java.awt.Color(49, 24, 140));
    btnSalirLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnSalirLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnSalirLabel.setText("Salir");
    btnSalirLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout btnSalirPanelLayout = new javax.swing.GroupLayout(btnSalirPanel);
    btnSalirPanel.setLayout(btnSalirPanelLayout);
    btnSalirPanelLayout.setHorizontalGroup(
      btnSalirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnSalirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btnSalirPanelLayout.setVerticalGroup(
      btnSalirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnSalirPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnSalirLabel)
        .addContainerGap(10, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnConsultarClientePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnConsultaCuentaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnCambiarPinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnDepositarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnRetirarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnTransferirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnTipoCambioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnConsultarSaldoActualPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnConsultarSaldoDolaresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnEstadoCuentaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnEstadoCuentaDolarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnEstatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnComisionTotalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(btnSalirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addComponent(principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnCrearCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnComisionCuentaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnConsultarClientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnConsultaCuentaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnCambiarPinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnDepositarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnRetirarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnTransferirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnTipoCambioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnConsultarSaldoActualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnConsultarSaldoDolaresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnEstadoCuentaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnEstadoCuentaDolarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnEstatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnComisionTotalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnComisionCuentaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSalirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(9, Short.MAX_VALUE))
    );

    bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 710));

    content.setBackground(new java.awt.Color(255, 255, 255));

    jLabel18.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
    jLabel18.setForeground(new java.awt.Color(0, 0, 0));
    jLabel18.setText(" ¡Bienvenida a iBanco!");

    jLabel19.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
    jLabel19.setText("Para comenzar, presione un click a cualquiera de las opciones que se despliegan ");

    jLabel20.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
    jLabel20.setText("al lado izquiero de la pantalla. Para finalizar, seleccione el botón Salir para cerrar");

    jLabel21.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
    jLabel21.setText("la aplicación.");

    jLabel22.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
    jLabel22.setText("Derechos reservados");

    javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
    content.setLayout(contentLayout);
    contentLayout.setHorizontalGroup(
      contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jLabel22)
        .addGap(19, 19, 19))
      .addGroup(contentLayout.createSequentialGroup()
        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(contentLayout.createSequentialGroup()
            .addGap(90, 90, 90)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(contentLayout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel21)
              .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        .addContainerGap(51, Short.MAX_VALUE))
    );
    contentLayout.setVerticalGroup(
      contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(contentLayout.createSequentialGroup()
        .addGap(58, 58, 58)
        .addComponent(jLabel18)
        .addGap(50, 50, 50)
        .addComponent(jLabel19)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel20)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel21)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
        .addComponent(jLabel22)
        .addContainerGap())
    );

    bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 830, 710));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnRegistrarClienteLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarClienteLabelMouseEntered
    btnRegistrarCliente.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnRegistrarClienteLabelMouseEntered

  private void btnRegistrarClienteLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarClienteLabelMouseExited
    btnRegistrarCliente.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnRegistrarClienteLabelMouseExited

  private void btnRegistrarClienteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarClienteLabelMouseClicked
    RegistrarCliente ventanaRegistrarCliente= new RegistrarCliente (new SimpleValidacionFactory());
    ShowPanel(ventanaRegistrarCliente);
  }//GEN-LAST:event_btnRegistrarClienteLabelMouseClicked

  private void principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalMouseClicked
    
  }//GEN-LAST:event_principalMouseClicked

  private void btnCrearCuentaLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaLMouseClicked
    CrearCuenta ventanaCrearCuenta = new CrearCuenta(new SimpleValidacionFactory());
    ShowPanel(ventanaCrearCuenta);
  }//GEN-LAST:event_btnCrearCuentaLMouseClicked

  private void btnCrearCuentaLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaLMouseEntered
    btnCrearCuenta.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnCrearCuentaLMouseEntered

  private void btnCrearCuentaLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCuentaLMouseExited
    btnCrearCuenta.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnCrearCuentaLMouseExited

  private void btnConsultarclienteLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarclienteLabelMouseEntered
     btnConsultarClientePanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnConsultarclienteLabelMouseEntered

  private void btnConsultarclienteLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarclienteLabelMouseExited
    btnConsultarClientePanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnConsultarclienteLabelMouseExited

  private void btnConsultarclienteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarclienteLabelMouseClicked
    ConsultarCliente ventanaConsultarCliente = new ConsultarCliente ();
    ShowPanel(ventanaConsultarCliente);
  }//GEN-LAST:event_btnConsultarclienteLabelMouseClicked

  private void btnConsultaCuentaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaCuentaLabelMouseEntered
    btnConsultaCuentaPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnConsultaCuentaLabelMouseEntered

  private void btnConsultaCuentaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaCuentaLabelMouseExited
    btnConsultaCuentaPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnConsultaCuentaLabelMouseExited

  private void btnConsultaCuentaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaCuentaLabelMouseClicked
    ConsultarCuenta ventanaConsultarCuenta = new ConsultarCuenta ();
    ShowPanel(ventanaConsultarCuenta);
  }//GEN-LAST:event_btnConsultaCuentaLabelMouseClicked

  private void btnCambiarPinLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarPinLabelMouseEntered
    btnCambiarPinPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnCambiarPinLabelMouseEntered

  private void btnCambiarPinLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarPinLabelMouseExited
    btnCambiarPinPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnCambiarPinLabelMouseExited

  private void btnCambiarPinLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarPinLabelMouseClicked
    CambiarPin ventanaCambiarPin = new CambiarPin (new SimpleValidacionFactory ());
    ShowPanel(ventanaCambiarPin);
  }//GEN-LAST:event_btnCambiarPinLabelMouseClicked

  private void btnDepositarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositarLabelMouseEntered
    btnDepositarPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnDepositarLabelMouseEntered

  private void btnDepositarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositarLabelMouseExited
    btnDepositarPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnDepositarLabelMouseExited

  private void btnDepositarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositarLabelMouseClicked
    Depositar ventanaDepositar = new Depositar (new SimpleValidacionFactory());
    ShowPanel(ventanaDepositar);
  }//GEN-LAST:event_btnDepositarLabelMouseClicked

  private void btnRetirarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarLabelMouseEntered
    btnRetirarPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnRetirarLabelMouseEntered

  private void btnRetirarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarLabelMouseExited
    btnRetirarPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnRetirarLabelMouseExited

  private void btnRetirarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarLabelMouseClicked
    Retirar ventanaRetirar = new Retirar (new SimpleValidacionFactory ());
    ShowPanel(ventanaRetirar);
  }//GEN-LAST:event_btnRetirarLabelMouseClicked

  private void btnTransferirLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferirLabelMouseEntered
    btnTransferirPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnTransferirLabelMouseEntered

  private void btnTransferirLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferirLabelMouseExited
    btnTransferirPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnTransferirLabelMouseExited

  private void btnTransferirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferirLabelMouseClicked
    Transferir ventanaTransferir = new Transferir (new SimpleValidacionFactory ());
    ShowPanel(ventanaTransferir);
  }//GEN-LAST:event_btnTransferirLabelMouseClicked

  private void btnTipoCambioLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoCambioLabelMouseEntered
    btnTipoCambioPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnTipoCambioLabelMouseEntered

  private void btnTipoCambioLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoCambioLabelMouseExited
    btnTipoCambioPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnTipoCambioLabelMouseExited

  private void btnTipoCambioLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoCambioLabelMouseClicked
    TipoCambio ventanaTipoCambio = new TipoCambio ();
    ShowPanel(ventanaTipoCambio);
  }//GEN-LAST:event_btnTipoCambioLabelMouseClicked

  private void btnConsultarSaldoActualLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoActualLabelMouseEntered
    btnConsultarSaldoActualPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnConsultarSaldoActualLabelMouseEntered

  private void btnConsultarSaldoActualLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoActualLabelMouseExited
    btnConsultarSaldoActualPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnConsultarSaldoActualLabelMouseExited

  private void btnConsultarSaldoActualLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoActualLabelMouseClicked
    ConsultaSaldoActual ventanaConsultaSaldoActual = new ConsultaSaldoActual(new SimpleValidacionFactory());
    ShowPanel(ventanaConsultaSaldoActual);
  }//GEN-LAST:event_btnConsultarSaldoActualLabelMouseClicked

  private void btnConsultarSaldoDolaresLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoDolaresLabelMouseEntered
    btnConsultarSaldoDolaresPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnConsultarSaldoDolaresLabelMouseEntered

  private void btnConsultarSaldoDolaresLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoDolaresLabelMouseExited
    btnConsultarSaldoDolaresPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnConsultarSaldoDolaresLabelMouseExited

  private void btnConsultarSaldoDolaresLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoDolaresLabelMouseClicked
    ConsultaSaldoActualDolares ventanaConsultaSaldoActualDolares = new ConsultaSaldoActualDolares (new SimpleValidacionFactory());
    ShowPanel(ventanaConsultaSaldoActualDolares);
  }//GEN-LAST:event_btnConsultarSaldoDolaresLabelMouseClicked

  private void btnEstadoCuentaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoCuentaLabelMouseEntered
    btnEstadoCuentaPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnEstadoCuentaLabelMouseEntered

  private void btnEstadoCuentaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoCuentaLabelMouseExited
    btnEstadoCuentaPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnEstadoCuentaLabelMouseExited

  private void btnEstadoCuentaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoCuentaLabelMouseClicked
    EstadoCuenta ventanaEstadoCuenta = new EstadoCuenta (new SimpleValidacionFactory());
    ShowPanel(ventanaEstadoCuenta);
  }//GEN-LAST:event_btnEstadoCuentaLabelMouseClicked

  private void btnEstadoCuentaDolarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoCuentaDolarLabelMouseEntered
    btnEstadoCuentaDolarPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnEstadoCuentaDolarLabelMouseEntered

  private void btnEstadoCuentaDolarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoCuentaDolarLabelMouseExited
    btnEstadoCuentaDolarPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnEstadoCuentaDolarLabelMouseExited

  private void btnEstadoCuentaDolarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoCuentaDolarLabelMouseClicked
    EstadoCuentaDolares ventanaEstadoCuentaDolares = new EstadoCuentaDolares (new SimpleValidacionFactory());
    ShowPanel(ventanaEstadoCuentaDolares);
  }//GEN-LAST:event_btnEstadoCuentaDolarLabelMouseClicked

  private void btnEstatusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatusLabelMouseEntered
    btnEstatusPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnEstatusLabelMouseEntered

  private void btnEstatusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatusLabelMouseExited
    btnEstatusPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnEstatusLabelMouseExited

  private void btnEstatusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatusLabelMouseClicked
    EstatusCuenta ventanaEstatusCuenta = new EstatusCuenta (new SimpleValidacionFactory());
    ShowPanel(ventanaEstatusCuenta);
  }//GEN-LAST:event_btnEstatusLabelMouseClicked

  private void btnComisionTotalLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComisionTotalLabelMouseEntered
    btnComisionTotalPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnComisionTotalLabelMouseEntered

  private void btnComisionTotalLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComisionTotalLabelMouseExited
    btnComisionTotalPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnComisionTotalLabelMouseExited

  private void btnComisionTotalLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComisionTotalLabelMouseClicked
    ComisionGanada ventanaComisionGanada = new ComisionGanada ();
    ShowPanel(ventanaComisionGanada);
  }//GEN-LAST:event_btnComisionTotalLabelMouseClicked

  private void btnComisionCuentaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComisionCuentaLabelMouseEntered
    btnComisionCuentaPanel.setBackground(new Color ( 115, 56, 242));
  }//GEN-LAST:event_btnComisionCuentaLabelMouseEntered

  private void btnComisionCuentaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComisionCuentaLabelMouseExited
    btnComisionCuentaPanel.setBackground(new Color ( 49, 24, 140));
  }//GEN-LAST:event_btnComisionCuentaLabelMouseExited

  private void btnComisionCuentaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComisionCuentaLabelMouseClicked
    ComisionGanadaCuenta ventanaComisionGanadaCuenta = new ComisionGanadaCuenta (new SimpleValidacionFactory ());
    ShowPanel(ventanaComisionGanadaCuenta);
  }//GEN-LAST:event_btnComisionCuentaLabelMouseClicked
  
  private void ShowPanel (JPanel p ) {
    p.setSize(830, 710);
    p.setLocation(0, 0);
    
    content.removeAll();
    content.add(p, BorderLayout.CENTER);
    content.revalidate();
    content.repaint();
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Menu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bg;
  private javax.swing.JLabel btnCambiarPinLabel;
  private javax.swing.JPanel btnCambiarPinPanel;
  private javax.swing.JLabel btnComisionCuentaLabel;
  private javax.swing.JPanel btnComisionCuentaPanel;
  private javax.swing.JLabel btnComisionTotalLabel;
  private javax.swing.JPanel btnComisionTotalPanel;
  private javax.swing.JLabel btnConsultaCuentaLabel;
  private javax.swing.JPanel btnConsultaCuentaPanel;
  private javax.swing.JPanel btnConsultarClientePanel;
  private javax.swing.JLabel btnConsultarSaldoActualLabel;
  private javax.swing.JPanel btnConsultarSaldoActualPanel;
  private javax.swing.JLabel btnConsultarSaldoDolaresLabel;
  private javax.swing.JPanel btnConsultarSaldoDolaresPanel;
  private javax.swing.JLabel btnConsultarclienteLabel;
  private javax.swing.JPanel btnCrearCuenta;
  private javax.swing.JLabel btnCrearCuentaL;
  private javax.swing.JLabel btnDepositarLabel;
  private javax.swing.JPanel btnDepositarPanel;
  private javax.swing.JLabel btnEstadoCuentaDolarLabel;
  private javax.swing.JPanel btnEstadoCuentaDolarPanel;
  private javax.swing.JLabel btnEstadoCuentaLabel;
  private javax.swing.JPanel btnEstadoCuentaPanel;
  private javax.swing.JLabel btnEstatusLabel;
  private javax.swing.JPanel btnEstatusPanel;
  private javax.swing.JPanel btnRegistrarCliente;
  private javax.swing.JLabel btnRegistrarClienteLabel;
  private javax.swing.JLabel btnRetirarLabel;
  private javax.swing.JPanel btnRetirarPanel;
  private javax.swing.JLabel btnSalirLabel;
  private javax.swing.JPanel btnSalirPanel;
  private javax.swing.JLabel btnTipoCambioLabel;
  private javax.swing.JPanel btnTipoCambioPanel;
  private javax.swing.JLabel btnTransferirLabel;
  private javax.swing.JPanel btnTransferirPanel;
  private javax.swing.JPanel content;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel19;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel principal;
  // End of variables declaration//GEN-END:variables
}
