/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logicadepresentacion.gui;

/**
 *
 * @author Alejandra Merino
 */
public class RegistrarCliente extends javax.swing.JPanel {

  /**
   * Creates new form RegistrarCliente
   */
  public RegistrarCliente() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bgRegistrarCliente = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    bgRegistrarCliente.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setBackground(new java.awt.Color(0, 0, 0));
    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setText("Registra un nuevo cliente");

    javax.swing.GroupLayout bgRegistrarClienteLayout = new javax.swing.GroupLayout(bgRegistrarCliente);
    bgRegistrarCliente.setLayout(bgRegistrarClienteLayout);
    bgRegistrarClienteLayout.setHorizontalGroup(
      bgRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bgRegistrarClienteLayout.createSequentialGroup()
        .addGap(203, 203, 203)
        .addComponent(jLabel1)
        .addContainerGap(305, Short.MAX_VALUE))
    );
    bgRegistrarClienteLayout.setVerticalGroup(
      bgRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bgRegistrarClienteLayout.createSequentialGroup()
        .addGap(80, 80, 80)
        .addComponent(jLabel1)
        .addContainerGap(614, Short.MAX_VALUE))
    );

    add(bgRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bgRegistrarCliente;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
