/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logicadepresentacion.gui;

import javax.swing.JOptionPane;
import logicacreacional.SimpleValidacionFactory;
import logicadeintegracion.gui.ControladorRetirar;
import logicadevalidacion.FondosInsuficientesExcepcion;
import logicadevalidacion.ValidacionCuenta;

/**
 *
 * @author Alejandra Merino
 */
public class Retirar extends javax.swing.JPanel {
    private SimpleValidacionFactory factoryValidacion;
    private ControladorRetirar control;
    private ValidacionCuenta validacionCuenta;
  /**
   * Creates new form Retirar
   */
    public Retirar(SimpleValidacionFactory pFactoryValidacion) {
      initComponents();
      factoryValidacion = pFactoryValidacion;
      control = new ControladorRetirar ();
      try {
            validacionCuenta = (ValidacionCuenta)(factoryValidacion.crearValidacion("ValidacionCuenta"));
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            System.out.println(ex.getMessage());
        }
    }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtNumeroCuenta = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    cbxMoneda = new javax.swing.JComboBox<>();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel4 = new javax.swing.JLabel();
    txtPinActual = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jSeparator3 = new javax.swing.JSeparator();
    txtPalabraSecreta = new javax.swing.JTextField();
    jSeparator4 = new javax.swing.JSeparator();
    jLabel6 = new javax.swing.JLabel();
    txtMontoRetiro = new javax.swing.JTextField();
    jSeparator5 = new javax.swing.JSeparator();
    btnRetirarPanel = new javax.swing.JPanel();
    btnRetirarLabel = new javax.swing.JLabel();
    btnValidarRetiroPanel = new javax.swing.JPanel();
    btnValidarRetiroLabel = new javax.swing.JLabel();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Realice un retiro");

    jLabel2.setText("Ingrese su número de cuenta:");

    txtNumeroCuenta.setBackground(new java.awt.Color(255, 255, 255));
    txtNumeroCuenta.setBorder(null);

    jLabel3.setText("Seleccione la moneda de su retiro:");

    cbxMoneda.setBackground(new java.awt.Color(255, 255, 255));
    cbxMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colones", "Dólares" }));

    jLabel4.setText("Ingrese el PIN de su cuenta:");

    txtPinActual.setBackground(new java.awt.Color(255, 255, 255));
    txtPinActual.setBorder(null);

    jLabel5.setText("Ingrese la palabra que recibió por mensaje de texto: ");

    txtPalabraSecreta.setBackground(new java.awt.Color(255, 255, 255));
    txtPalabraSecreta.setForeground(new java.awt.Color(0, 0, 0));
    txtPalabraSecreta.setBorder(null);

    jLabel6.setText("Ingrese el monto del retiro:");

    txtMontoRetiro.setBackground(new java.awt.Color(255, 255, 255));
    txtMontoRetiro.setBorder(null);

    btnRetirarLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
    btnRetirarLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnRetirarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnRetirarLabel.setText("Retirar");
    btnRetirarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRetirarLabel.setEnabled(false);
    btnRetirarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnRetirarLabelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btnRetirarPanelLayout = new javax.swing.GroupLayout(btnRetirarPanel);
    btnRetirarPanel.setLayout(btnRetirarPanelLayout);
    btnRetirarPanelLayout.setHorizontalGroup(
      btnRetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnRetirarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    btnRetirarPanelLayout.setVerticalGroup(
      btnRetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnRetirarPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnRetirarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        .addContainerGap())
    );

    btnValidarRetiroLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
    btnValidarRetiroLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnValidarRetiroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnValidarRetiroLabel.setText("Validar");
    btnValidarRetiroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnValidarRetiroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnValidarRetiroLabelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btnValidarRetiroPanelLayout = new javax.swing.GroupLayout(btnValidarRetiroPanel);
    btnValidarRetiroPanel.setLayout(btnValidarRetiroPanelLayout);
    btnValidarRetiroPanelLayout.setHorizontalGroup(
      btnValidarRetiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnValidarRetiroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    btnValidarRetiroPanelLayout.setVerticalGroup(
      btnValidarRetiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnValidarRetiroPanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnValidarRetiroLabel)
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(182, 182, 182)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtMontoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel6)
                .addComponent(jSeparator3)
                .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                  .addComponent(cbxMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel2)
                .addComponent(txtNumeroCuenta)
                .addComponent(jSeparator1)
                .addComponent(jSeparator2)
                .addComponent(jSeparator4)
                .addComponent(jSeparator5)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addComponent(jLabel4)
                      .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtPinActual))
                  .addGap(18, 18, 18)
                  .addComponent(btnValidarRetiroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(txtPalabraSecreta))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(353, 353, 353)
            .addComponent(btnRetirarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(185, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(93, 93, 93)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(cbxMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtPinActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnValidarRetiroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPalabraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtMontoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnRetirarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(230, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnRetirarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarLabelMouseClicked
    validacionCuenta.validarDatosRetiro(txtPalabraSecreta.getText(), 
            txtMontoRetiro.getText(),txtNumeroCuenta.getText());
    if(validacionCuenta.esValido) {
      try {
        control.controlarRetiro(txtNumeroCuenta.getText(),
                txtMontoRetiro.getText(), (String) cbxMoneda.getSelectedItem());
        validacionCuenta.setResultado(control.getMensaje());
      } catch (FondosInsuficientesExcepcion ex) {
        validacionCuenta.setResultado(ex.toString());
      }
    } JOptionPane.showMessageDialog(this, validacionCuenta.resultado);
    validacionCuenta.setResultado("");
    validacionCuenta.setValido();
  }//GEN-LAST:event_btnRetirarLabelMouseClicked

  private void btnValidarRetiroLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidarRetiroLabelMouseClicked
    validacionCuenta.setResultado("");
    validacionCuenta.setValido();
    validacionCuenta.validarDatosPrevioRetiro(txtNumeroCuenta.getText(), 
            txtPinActual.getText());
    if(validacionCuenta.esValido) {
      txtNumeroCuenta.setEditable(false);
      txtPinActual.setEditable(false);
      btnRetirarLabel.setEnabled(true);
      control.controlarEnvioSms(txtNumeroCuenta.getText());
      validacionCuenta.setResultado(control.getMensaje());
      validacionCuenta.setPalabraSecreta(control.getPalabraSecreta());
    } JOptionPane.showMessageDialog(this, validacionCuenta.resultado);
  }//GEN-LAST:event_btnValidarRetiroLabelMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel btnRetirarLabel;
  private javax.swing.JPanel btnRetirarPanel;
  private javax.swing.JLabel btnValidarRetiroLabel;
  private javax.swing.JPanel btnValidarRetiroPanel;
  private javax.swing.JComboBox<String> cbxMoneda;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JTextField txtMontoRetiro;
  private javax.swing.JTextField txtNumeroCuenta;
  private javax.swing.JTextField txtPalabraSecreta;
  private javax.swing.JTextField txtPinActual;
  // End of variables declaration//GEN-END:variables
}
