/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logicadepresentacion.gui;

import javax.swing.JOptionPane;
import logicadeintegracion.gui.ControladorTipoCambio;

/**
 *
 * @author Alejandra Merino
 */
public class TipoCambio extends javax.swing.JPanel {
  private ControladorTipoCambio control;

  /**
   * Creates new form TipoCambio
   */
  public TipoCambio() {
    initComponents();
    control = new ControladorTipoCambio ();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    cbxTipoOperacion = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    btnConsultarPanel = new javax.swing.JPanel();
    btnConsultaLabel = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtResultadoTC = new javax.swing.JTextArea();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Consulte el tipo de cambio del dia");

    cbxTipoOperacion.setBackground(new java.awt.Color(255, 255, 255));
    cbxTipoOperacion.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
    cbxTipoOperacion.setForeground(new java.awt.Color(102, 102, 102));
    cbxTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compra", "Venta" }));

    jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
    jLabel2.setText("Selecctione el tipo de operación:");

    btnConsultaLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
    btnConsultaLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnConsultaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnConsultaLabel.setText("Consultar");
    btnConsultaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnConsultaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnConsultaLabelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btnConsultarPanelLayout = new javax.swing.GroupLayout(btnConsultarPanel);
    btnConsultarPanel.setLayout(btnConsultarPanelLayout);
    btnConsultarPanelLayout.setHorizontalGroup(
      btnConsultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnConsultaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    btnConsultarPanelLayout.setVerticalGroup(
      btnConsultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnConsultarPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnConsultaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        .addContainerGap())
    );

    jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
    jLabel4.setText("Detalle:");

    txtResultadoTC.setBackground(new java.awt.Color(255, 255, 255));
    txtResultadoTC.setColumns(20);
    txtResultadoTC.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
    txtResultadoTC.setForeground(new java.awt.Color(102, 102, 102));
    txtResultadoTC.setRows(5);
    txtResultadoTC.setBorder(null);
    jScrollPane1.setViewportView(txtResultadoTC);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane1)
          .addComponent(jLabel4)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cbxTipoOperacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(364, 364, 364)
        .addComponent(btnConsultarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(365, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(64, 64, 64)
        .addComponent(jLabel1)
        .addGap(46, 46, 46)
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addComponent(cbxTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(29, 29, 29)
        .addComponent(btnConsultarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(32, 32, 32)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(280, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnConsultaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaLabelMouseClicked
    control.controlarTipoCambio((String) cbxTipoOperacion.getSelectedItem());
    txtResultadoTC.setText(control.getMensaje());
  }//GEN-LAST:event_btnConsultaLabelMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel btnConsultaLabel;
  private javax.swing.JPanel btnConsultarPanel;
  private javax.swing.JComboBox<String> cbxTipoOperacion;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtResultadoTC;
  // End of variables declaration//GEN-END:variables
}
