/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logicadepresentacion.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logicadeintegracion.gui.ControladorRetirar;
import logicadeintegracion.gui.ControladorTransferencia;
import logicadevalidacion.FondosInsuficientesExcepcion;
import logicadevalidacion.ValidacionCuenta;

/**
 *
 * @author Alejandra Merino
 */
public class Transferir extends javax.swing.JPanel {
  private ValidacionCuenta validacionCuenta;
  private ControladorTransferencia control;
  /**
   * Creates new form Transferir
   */
  public Transferir() {
    initComponents();
    validacionCuenta = new ValidacionCuenta ();
    control = new ControladorTransferencia ();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnValidarPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtNumeroCuenta = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    txtPinActual = new javax.swing.JTextField();
    jSeparator2 = new javax.swing.JSeparator();
    jPanel2 = new javax.swing.JPanel();
    btnValidarLabel = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtPalabraSecreta = new javax.swing.JTextField();
    jSeparator3 = new javax.swing.JSeparator();
    jLabel6 = new javax.swing.JLabel();
    txtMontoTrans = new javax.swing.JTextField();
    jSeparator4 = new javax.swing.JSeparator();
    jLabel7 = new javax.swing.JLabel();
    txtNumeroCuentaTrans = new javax.swing.JTextField();
    jSeparator5 = new javax.swing.JSeparator();
    btnTransferirPanel = new javax.swing.JPanel();
    btnTransferirLabel = new javax.swing.JLabel();

    btnValidarPanel.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Realice una transferencia");

    jLabel2.setText("Ingrese su número de cuenta:");

    txtNumeroCuenta.setBackground(new java.awt.Color(255, 255, 255));
    txtNumeroCuenta.setForeground(new java.awt.Color(102, 102, 102));
    txtNumeroCuenta.setBorder(null);

    jLabel3.setText("Ingrese el PIN de su cuenta:");

    txtPinActual.setBackground(new java.awt.Color(255, 255, 255));
    txtPinActual.setForeground(new java.awt.Color(102, 102, 102));
    txtPinActual.setBorder(null);

    btnValidarLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
    btnValidarLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnValidarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnValidarLabel.setText("Validar");
    btnValidarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnValidarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnValidarLabelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnValidarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnValidarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jLabel5.setText("Ingrese la palabra que recibió por mensaje de texto: ");

    txtPalabraSecreta.setBackground(new java.awt.Color(255, 255, 255));
    txtPalabraSecreta.setBorder(null);

    jLabel6.setText("Ingrese el monto a transferir: ");

    txtMontoTrans.setBackground(new java.awt.Color(255, 255, 255));
    txtMontoTrans.setBorder(null);

    jLabel7.setText("Ingrese el número de cuenta a transferir:");

    txtNumeroCuentaTrans.setBackground(new java.awt.Color(255, 255, 255));
    txtNumeroCuentaTrans.setBorder(null);

    btnTransferirLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
    btnTransferirLabel.setForeground(new java.awt.Color(255, 255, 255));
    btnTransferirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnTransferirLabel.setText("Transferir");
    btnTransferirLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnTransferirLabel.setEnabled(false);
    btnTransferirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnTransferirLabelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btnTransferirPanelLayout = new javax.swing.GroupLayout(btnTransferirPanel);
    btnTransferirPanel.setLayout(btnTransferirPanelLayout);
    btnTransferirPanelLayout.setHorizontalGroup(
      btnTransferirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnTransferirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    btnTransferirPanelLayout.setVerticalGroup(
      btnTransferirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnTransferirPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnTransferirLabel)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout btnValidarPanelLayout = new javax.swing.GroupLayout(btnValidarPanel);
    btnValidarPanel.setLayout(btnValidarPanelLayout);
    btnValidarPanelLayout.setHorizontalGroup(
      btnValidarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(btnValidarPanelLayout.createSequentialGroup()
        .addGroup(btnValidarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(btnValidarPanelLayout.createSequentialGroup()
            .addGap(168, 168, 168)
            .addGroup(btnValidarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel7)
              .addComponent(jLabel6)
              .addComponent(jLabel5)
              .addComponent(jLabel3)
              .addComponent(jLabel2)
              .addComponent(txtNumeroCuenta)
              .addComponent(jSeparator1)
              .addComponent(jSeparator2)
              .addGroup(btnValidarPanelLayout.createSequentialGroup()
                .addComponent(txtPinActual, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addComponent(txtPalabraSecreta)
              .addComponent(jSeparator3)
              .addComponent(txtMontoTrans)
              .addComponent(jSeparator4)
              .addComponent(txtNumeroCuentaTrans)
              .addComponent(jSeparator5)))
          .addGroup(btnValidarPanelLayout.createSequentialGroup()
            .addGap(354, 354, 354)
            .addComponent(btnTransferirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(196, Short.MAX_VALUE))
    );
    btnValidarPanelLayout.setVerticalGroup(
      btnValidarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnValidarPanelLayout.createSequentialGroup()
        .addGap(61, 61, 61)
        .addComponent(jLabel1)
        .addGap(27, 27, 27)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(btnValidarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtPinActual))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPalabraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtMontoTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNumeroCuentaTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnTransferirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(268, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnValidarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnValidarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnValidarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidarLabelMouseClicked
    validacionCuenta.validarDatosPrevioRetiro(txtNumeroCuenta.getText(), 
            txtPinActual.getText());
    if(validacionCuenta.esValido) {
      txtNumeroCuenta.setEditable(false);
      txtPinActual.setEditable(false);
      btnTransferirLabel.setEnabled(true);
      control.controlarEnvioSms(txtNumeroCuenta.getText());
      validacionCuenta.setResultado(control.getMensaje());
      validacionCuenta.setPalabraSecreta(control.getPalabraSecreta());
    } JOptionPane.showMessageDialog(this, validacionCuenta.resultado);
  }//GEN-LAST:event_btnValidarLabelMouseClicked

  private void btnTransferirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferirLabelMouseClicked
    validacionCuenta.validarDatosTransferencia(txtPalabraSecreta.getText(),
            txtMontoTrans.getText() , txtNumeroCuentaTrans.getText(), 
            txtNumeroCuenta.getText());
    if(validacionCuenta.esValido) {
      try { 
        control.controlarTransferencia(txtNumeroCuenta.getText(),
                txtMontoTrans.getText(), txtNumeroCuentaTrans.getText());
        validacionCuenta.setResultado(control.getMensaje());
      } catch (FondosInsuficientesExcepcion ex) {
        validacionCuenta.setResultado(ex.toString());
      }
    } JOptionPane.showMessageDialog(this, validacionCuenta.resultado);
  }//GEN-LAST:event_btnTransferirLabelMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel btnTransferirLabel;
  private javax.swing.JPanel btnTransferirPanel;
  private javax.swing.JLabel btnValidarLabel;
  private javax.swing.JPanel btnValidarPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JTextField txtMontoTrans;
  private javax.swing.JTextField txtNumeroCuenta;
  private javax.swing.JTextField txtNumeroCuentaTrans;
  private javax.swing.JTextField txtPalabraSecreta;
  private javax.swing.JTextField txtPinActual;
  // End of variables declaration//GEN-END:variables
}
